- .github/workflows/publish.yml
- applications/klighd-vscode/package.json
- yarn.lock
Extends the distribution script for the `klighd-vscode` package to also publish to Open VSX.
To save a few CI seconds, the script is further changed to not package the extension. Instead, the extension is only packaged once before it is distributed. Previously, a call to `vsce publish` would have also packaged the extension.
> Add Open VSX as distribution target

- README.md
- applications/klighd-vscode/README.md
- applications/klighd-vscode/package.json
Adds a small disclaimer to the root README and extension README to inform the user about the complexity of building a KLighD powered language server.
This has been an advice by @a-sr since it is quite complex to build a language server. Users that want to integrate the extension might not be aware of that.
> Add disclaimer about language server complexity

- packages/klighd-core/src/options/components/option-inputs.tsx
- packages/klighd-core/styles/options.css
This fixes the issues identified in #10. Text inputs now use a vertical layout with the label placed on top. Furthermore, they are styled using the available theme, similar to the synthesis selector.
The issue (#10) contains a screenshot from before the fix. After the fix:
closes #10
> Core: Fix layout used by text input options (#10)

- applications/klighd-vscode/README.md
- applications/klighd-vscode/src/constants.ts
- applications/klighd-vscode/src/extension.ts
This PR adds a new command to the `klighd-vscode` extension that allows other extensions to dispatch an Sprotty action in all open webviews that belong to the host extension.
Usage (documented in the README as well):
```typescript
// - refId: your registration id returned from the setLanguageClient command
// - action: a valid Sprotty action that is send to open diagram views.
vscode.commands.executeCommand("klighd-vscode.dispatchAction", refId: string, action: Action);
```
> klighd-vscode: add dispatch-action command for other extensions

- examples/local-documentation/README.md
- examples/local-documentation/first-embed.elkt
- examples/local-documentation/index.html
- examples/local-documentation/second-embed.sctx
This PR adds an example and usage guide on "Using the CLI for Local Documentation".
Sadly, before a user is able to try the example, the diagram-file paths in the html have to be modified to match the local file structure. I tried to use relative paths hoping that it would work if the CLI is used in the same folder, but it generated an exception on the LS.
> Docs: Add a local documentation example

- applications/klighd-vscode/src/klighd-extension.ts
A rename proposed for #13 caused this problem, since "in" checks are not correctly refactored.
This PR also removes the "in" checks and just calls the method if it exists on the object.
> fix(klighd-vscode): sync with editor is not toggled

- packages/klighd-core/src/depth-map.ts
- packages/klighd-core/src/options/render-options-registry.ts
- packages/klighd-core/src/skgraph-models.ts
- packages/klighd-core/src/views-common.ts
- packages/klighd-core/src/views-rendering.tsx
Initially node titles were implemented specific to KTexts, so that any KText could be a node title which would be scaled up within its parent rendering when zoomed out far enough to make that title illegible.
This PR rethinks the core idea and allows the same concept for any rendering. So now any rendering can be set to be the node title and that entire rendering (e.g. formatted text) will be scaled accordingly.
Also re-organizes some code used multiple times.
> Node titles allow for any rendering, not only KTexts

- packages/klighd-core/src/views-rendering.tsx
Since text is vertically centered one has to calculate the start y coordinate by taking the width of the lines up to the middle line into account.
> Fix multiline label position calculation.

- packages/klighd-core/src/hover/popup-provider.ts
- packages/klighd-core/src/options/options-blacklist.ts
- packages/klighd-core/src/skgraph-models.ts
- packages/klighd-core/src/skgraph-utils.ts
- packages/klighd-core/src/views-common.ts
- packages/klighd-core/src/views-rendering.tsx
- packages/klighd-core/src/views.tsx
- packages/klighd-interactive/src/constraint-classes.ts
- packages/klighd-interactive/src/interactive-view.tsx
- packages/klighd-interactive/src/klighd-interactive-mouselistener.ts
- packages/klighd-interactive/src/layered/constraint-utils.ts
- packages/klighd-interactive/src/layered/layered-interactive-view.tsx
- packages/klighd-interactive/src/rect-packing/constraint-util.ts
This changes the way elk properties are accessed by the client.
Instead of the NodeProperties class, properties are now a map<string, unknown>, where the key is the the fully qualified name such as "org.eclipse.elk.algorithm"
Because the property types are now unknown, they have to be explicitly cast by the developer meaning the developer has to know the type of the property. Currently all the used properties are primitive types, but more complex types also exist and may need to be dealt with nicely. There may be some more checks necessary to ensure non-existent properties aren't being accessed, but I haven't found any such cases yet. 
[KGraphMappingUtil](https://github.com/kieler/KLighD/blob/72d79588917b5ef7c0e7b970c380d1584dd97419/plugins/de.cau.cs.kieler.klighd.lsp/src/de/cau/cs/kieler/ …
> update properties to be accessed using <string,unknown> map

- packages/klighd-core/src/views-rendering.tsx
> Disallow non-closed line renderings (e.g. polylines, splines) to be filled with any color

- packages/klighd-core/src/options/components/option-inputs.tsx
- packages/klighd-core/src/options/option-models.ts
- packages/klighd-core/src/options/options-renderer.tsx
Just a small change to allow to have a more descriptive text shown when hovering over synthesis options. Follows the behavior of hover feedback for layout options.
If no description is set, the name of the option is shown as the tooltip instead.
Linked to Server change in [#108 in KLighD](https://github.com/kieler/KLighD/pull/108)
To be merged once new KLighD nightly build host is up again.
> Added descriptions for synthesis options and show them in tooltips on hover.

- packages/klighd-core/src/skgraph-models.ts
Resolves #73 
The tooltip is already stored in the properties, this PR removes the unused tooltip fields.
[Server-side PR](https://github.com/kieler/KLighD/pull/115)
> remove unused tooltip field

- packages/klighd-core/src/skgraph-models.ts
- packages/klighd-core/src/skgraph-utils.ts
- packages/klighd-core/src/views-rendering.tsx
Make scaled up title renderings click-through if no actions are defined on that rendering.
Fixes #90.
This does not replicate the Piccolo behavior 100%, as there action execution is handled front-to-back on the canvas, we here do the execution child-to-parents, which is not necessarily the same.
> fixed klighd action execution to not care about selectability, but for action defintion as in its Piccolo counterpart.

- packages/klighd-core/src/skgraph-models.ts
- packages/klighd-core/src/views-common.ts
- packages/klighd-core/src/views-rendering.tsx
- packages/klighd-core/src/views-styles.tsx
Replicates same behavior as in klighd.piccolo. With this root renderings of selected elements with no defined selection style will have a grey background and dashed outline resp. bold text.
> Show a default selection style if none is defined.

- packages/klighd-interactive/src/klighd-interactive-mouselistener.ts
Otherwise clicking on nodes in elkt models would cause the refresh diagram action caused by this as well as a FocusAndContextAction defined onClick on the graph elements, causing a duplicate update request which may cause issues.
Any objections to this change @soerendomroes ?
> fix: interactive: do not intentionally update the diagram if nothing changed.

- applications/klighd-vscode/src/klighd-extension.ts
file urls such as `file:///c:/workspace/some.file` get different encodings by the URL encoder on the server (no further encoding for any character in this case) and the VS Code API (resulting in `file:///c%3A/workspace/some.file`) in some cases, this fixes an issue emerging from that for synchronizing the text when clicking on diagram elements.
> Fixes an encoding issue on Windows synchronizing diagram elements to text.

- applications/klighd-vscode/src/extension.ts
- applications/klighd-vscode/src/klighd-extension.ts
- applications/klighd-vscode/src/klighd-webview-reopener.ts
- applications/klighd-vscode/src/klighd-webview.ts
- applications/klighd-vscode/src/storage/storage-service.ts
Since the old webviewPanel does not refer to the old `SprottyWebview` (which is a `KlighdWebview`) cannot be readded to the list of available `KlighdWebview`s in `KlighdExtension` and the old panel cannot be used during the creation of a new `KlighdWebview` since it is `readonly`, we recreate the Diagram on the start of the extension for the currently active editor.
> Reopen new diagram widget on start for current active editor.

- applications/klighd-vscode/src/klighd-webview-reopener.ts
The diagram did not open if initially, no active text editor existed. Now the diagram opens when a text editor is selected and not if one was selected on startup.
(Everything or course only if the diagram was not closed)
> Open diagram if an editor is eventually selected.

- packages/klighd-core/src/views-common.ts
- packages/klighd-core/src/views-rendering.tsx
Fixes the child offsets for graphs with offset child areas.
Fixes the width and height of ellipses and rectangles to represent the correct bounding box of the renderings, not the middle points of their strokes.
Fixes #68
May fix #82
> child placement and rendering bounding box fixes

- packages/klighd-core/src/views-common.ts
- packages/klighd-core/src/views-rendering.tsx
- packages/klighd-core/src/views-styles.tsx
- packages/klighd-core/src/views.tsx
Fixes wrong style propagation for arrow heads, during simulation and for some more abstract edge-cases, matching the behavior in KLighD with Piccolo.
> Fix style propagation and order of style handling.

- packages/klighd-core/src/views-rendering.tsx
- packages/klighd-core/src/views-styles.tsx
Feat: allows to have a background for KTexts (e.g. transition comments in SCCharts)
Fix: fixes the default selection style
> Text rendering fixes

- packages/klighd-core/src/bookmarks/bookmark-panel.tsx
- packages/klighd-core/src/options/general-panel.tsx
- packages/klighd-core/src/options/options-panel.tsx
- packages/klighd-core/src/sidebar/sidebar-panel.ts
- packages/klighd-core/src/sidebar/sidebar-panel.tsx
- packages/klighd-core/src/views-rendering.tsx
1. switched tabs, so that options are at first, general second, and bookmarks at last.
2. also gave them static values, because general was at -10 before and the others at default (0)
3. let sidebar-panel init the quickactionbar. now options and general inherit it. 
--> now options has a quickactionbar aswell.
> Core: switched tabs + added quickbar for options

- applications/klighd-cli/server/klighd.ts
Previously the "title" used to show the executable name showed not the application name, but the command line name. This now always displays "klighd-linux", "klighd-win.exe" etc.
> cli: fixed example calls in help text to show the executable name.

- package.json
- tsconfig.json
- yarn.lock
This changes some compiler options, especially to allow mocha to test .tsx files or test files transitively requiring other .tsx files.
This PR does not break anything in the current running system, but we should consider upgrading more versions and maybe the typescript compiler settings in the whole project, as started in the testS branch.
> allow tests with jsx dependencies

- .github/workflows/package.yml
see https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
> Update Deprecated Actions. Bump update-artifact to v4

- packages/klighd-core/src/proxy-view/proxy-view-actions.ts
- packages/klighd-core/src/proxy-view/proxy-view-util.ts
- packages/klighd-core/src/proxy-view/proxy-view.tsx
In the CLI, the base ID does not start with the hardcoded keith-diagram_sprotty, so parts of the proxies did not work. This replaces the hardcoded string with the baseDiv option set for the diagram. Furthermore, we now make sure to initialize the proxy view with the current view options at startup and not only do that on change (which does not happen in the CLI at start by default).
Related to #170
> fixes option initialization for and handling of proxies in the CLI.

- packages/klighd-core/src/diagram-server.ts
- packages/klighd-core/src/views-rendering.tsx
A first implementation to include images in the SVG outside of the bundled language server jar in the diagram. URIs available to the application can be used with this, e.g. URLs to images found online.
To refer to a URI image, add a KImage to the model with `bundleName = "URI"` and the URI in the `imagePath` attribute.
This implementation just refers to those images, a different implementation also enabling to refer to e.g. image files next to the visualized model will be worth expanding on this feature, as well as downloading and embedding the images in the SVG instead of linking to them for better compatibility during SVG export.
> Allow KImages to refer to arbitrary URIs, which will be linked in the SVG

- packages/klighd-core/src/views-rendering.tsx
Fixes #186
This implements the alternative solution is to add the image in the top-level defs of the SVG and link to it on each occasion instead.
> reuse kimages instead of embedding multiple times.

- packages/klighd-core/src/depth-map.ts
fix: move scaleFactor and absolute position calculation to a more lenient check, calculating the values also for children not in child areas.
Fixes #189.
> Scale Factor calculation fix

- applications/klighd-cli/server/klighd.ts
- applications/klighd-cli/server/main.ts
This way a web-hosted CLI tool can now for example bind to 0.0.0.0 and be routed further via docker container. Default does not use this option and still hosts on localhost only.
> cli: add option -a --address to specify where the CLI tool should be hosted.

- packages/klighd-core/src/views-rendering.tsx
Seems like a minor change, but if a diagram is centered, its scaling is set equal to 1, causing the title scaling to just kick in, although it does not scale anything yet. This removes the scaling at this exact 1-to-1 scaling for centered diagrams and lets it only kick in for zoomed out diagrams.
> Only scale up titles if scaling is *strictly* larger than 1

- applications/klighd-vscode/package.json
- applications/klighd-vscode/webpack.config.js
for production (build/package), do not use source maps, during development (watch), use the correct ones to make webview and extension debuggable.
This makes the generated extension code as small and efficient as possible (minified) when using the build/package commands and debuggable and readable when using the watch command.
> Improve production/development minimization/debuggability

- applications/klighd-vscode/src/klighd-webview-reopener.ts
During adoption to Sprotty 0.13 another way of updating the diagram was introduced that always requests a diagram when the editor is switched. When opening VS Code now with no editor in focus (e.g. when the diagram was in focus, which is not re-opened by VS Code by default), clicking on an editor triggered this newly introduced switch AND this now-removed code we had for exactly that use case. As this is now superfluous and causes duplicated requests, this removes that issue.
See #162
> Removes the double diagram request on opening VS Code with no editor in focus

- packages/klighd-core/src/views-rendering.tsx
- packages/klighd-core/src/views-styles.tsx
Adds the ability to render KLighD's dashOffset for custom line styles.
> core: implement dash offset for custom line styles

- packages/klighd-core/src/options/options-blacklist.ts
re-enables an option from the EObjectFallbackSynthesis, working again since kieler/KLighD#224
> re-enable another now-working synthesis option

- packages/klighd-core/src/options/render-options-registry.ts
- packages/klighd-core/src/views-styles.tsx
- the scale introduced by topdown layout is also considered now
- the minimum line width turns into minimum line scale. That is, differences in line width as set by the synthesis are taken into account and all lines just have a minimum scale that they should have on screen. E.g., a line with a synthesis width of 3px and a minimum scale of 0.5 will always have at least a width on screen of 1.5px, etc.
> turn minimum line width into semantic line scaling. Also consider topdown layout scale.

- packages/klighd-core/src/filtering/parser.ts
- packages/klighd-core/src/filtering/reserved-structural-tags.ts
- packages/klighd-core/src/filtering/semantic-filtering-util.ts
- packages/klighd-core/test/filtering/parser.test.ts
Introduces pre-defined structural tags. Common graph-structural properties can be filtered without requiring a synthesis author to add this information to the semantic tags.
Tags can be overridden by synthesis authors if desired. If the tag exists in the properties then that value is used rather than executing the defined behaviour.
The following table lists the new tags and their effects and whether a test has been written yet:
| tag | # | $ | has unit test |
|--------|--------|--------|---------|
| children | true if element has children | number of children | <ul><li>- [x] </li></ul> |
| isNode | true if element is node | *not reserved* | <ul><li>- [x] </li></ul> |
| isEdge | true if element is edge | *not reserved* | <ul><li>- [x] </li></ul> |
| isPort | true if element is port | *not …
> Add pre-defined structural tags

- packages/klighd-core/src/filtering/reserved-structural-tags.ts
- packages/klighd-core/test/filtering/reserved-structural-tags.test.ts
- descriptions for reserved tags can now be retrieved
- two new functions provide a list of all reserved tags
- add new tags #childNodes and $childNodes
> Add documentation to reserved tags

- applications/klighd-vscode/package.json
- applications/klighd-vscode/src/commandContributions.ts
- packages/klighd-core/src/sidebar/sidebar.tsx
- packages/klighd-core/styles/main.css
Currently, I do not know how to reset this variable properly when closing the sidebar.
Moreover, I seem to be missing some padding here, since the diagram is a little cut-off.
> Add css property to limit diagram size by sidebar.

- packages/klighd-core/src/di.config.ts
- packages/klighd-core/src/layout-config.ts
fixes the sub-issue of #139. With this change, every layout algorithm can be used via the "algorithm" property again for client-side layout.
> fix string layout option handling in elkjs layout configurator

- packages/klighd-core/src/views-rendering.tsx
- packages/klighd-core/src/views.tsx
- no longer incorrectly applies scale to junction points
- top-down support for non-childarea children
> Correct handling of top-down scale factor in rendering
